// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: turnip/v1/operation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationService_ExecuteOperation_FullMethodName = "/turnip.v1.OperationService/ExecuteOperation"
)

// OperationServiceClient is the client API for OperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperationService carries the Runner -> Server side of an Operation's
// execution. ExecuteOperation is client-streaming: the Runner is the sole
// producer of everything in this exchange (it has the cloned repo and the
// tool binary; the Server has neither), so it opens the stream, sends one
// Start, any number of Log lines, then one Result, then closes its send
// side; the Server sends a single Ack once it has durably received the
// whole stream.
type OperationServiceClient interface {
	ExecuteOperation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecuteOperationRequest, ExecuteOperationResponse], error)
}

type operationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationServiceClient(cc grpc.ClientConnInterface) OperationServiceClient {
	return &operationServiceClient{cc}
}

func (c *operationServiceClient) ExecuteOperation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecuteOperationRequest, ExecuteOperationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperationService_ServiceDesc.Streams[0], OperationService_ExecuteOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteOperationRequest, ExecuteOperationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperationService_ExecuteOperationClient = grpc.ClientStreamingClient[ExecuteOperationRequest, ExecuteOperationResponse]

// OperationServiceServer is the server API for OperationService service.
// All implementations must embed UnimplementedOperationServiceServer
// for forward compatibility.
//
// OperationService carries the Runner -> Server side of an Operation's
// execution. ExecuteOperation is client-streaming: the Runner is the sole
// producer of everything in this exchange (it has the cloned repo and the
// tool binary; the Server has neither), so it opens the stream, sends one
// Start, any number of Log lines, then one Result, then closes its send
// side; the Server sends a single Ack once it has durably received the
// whole stream.
type OperationServiceServer interface {
	ExecuteOperation(grpc.ClientStreamingServer[ExecuteOperationRequest, ExecuteOperationResponse]) error
	mustEmbedUnimplementedOperationServiceServer()
}

// UnimplementedOperationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationServiceServer struct{}

func (UnimplementedOperationServiceServer) ExecuteOperation(grpc.ClientStreamingServer[ExecuteOperationRequest, ExecuteOperationResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteOperation not implemented")
}
func (UnimplementedOperationServiceServer) mustEmbedUnimplementedOperationServiceServer() {}
func (UnimplementedOperationServiceServer) testEmbeddedByValue()                          {}

// UnsafeOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationServiceServer will
// result in compilation errors.
type UnsafeOperationServiceServer interface {
	mustEmbedUnimplementedOperationServiceServer()
}

func RegisterOperationServiceServer(s grpc.ServiceRegistrar, srv OperationServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationService_ServiceDesc, srv)
}

func _OperationService_ExecuteOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OperationServiceServer).ExecuteOperation(&grpc.GenericServerStream[ExecuteOperationRequest, ExecuteOperationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperationService_ExecuteOperationServer = grpc.ClientStreamingServer[ExecuteOperationRequest, ExecuteOperationResponse]

// OperationService_ServiceDesc is the grpc.ServiceDesc for OperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turnip.v1.OperationService",
	HandlerType: (*OperationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteOperation",
			Handler:       _OperationService_ExecuteOperation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "turnip/v1/operation.proto",
}
