// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: turnip/v1/operation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOperationRequest) Reset() {
	*x = ExecuteOperationRequest{}
	mi := &file_turnip_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOperationRequest) ProtoMessage() {}

func (x *ExecuteOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turnip_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOperationRequest.ProtoReflect.Descriptor instead.
func (*ExecuteOperationRequest) Descriptor() ([]byte, []int) {
	return file_turnip_v1_operation_proto_rawDescGZIP(), []int{0}
}

type ExecuteOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOperationResponse) Reset() {
	*x = ExecuteOperationResponse{}
	mi := &file_turnip_v1_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOperationResponse) ProtoMessage() {}

func (x *ExecuteOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turnip_v1_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOperationResponse.ProtoReflect.Descriptor instead.
func (*ExecuteOperationResponse) Descriptor() ([]byte, []int) {
	return file_turnip_v1_operation_proto_rawDescGZIP(), []int{1}
}

var File_turnip_v1_operation_proto protoreflect.FileDescriptor

const file_turnip_v1_operation_proto_rawDesc = "" +
	"\n" +
	"\x19turnip/v1/operation.proto\x12\tturnip.v1\"\x19\n" +
	"\x17ExecuteOperationRequest\"\x1a\n" +
	"\x18ExecuteOperationResponse2q\n" +
	"\x10OperationService\x12]\n" +
	"\x10ExecuteOperation\x12\".turnip.v1.ExecuteOperationRequest\x1a#.turnip.v1.ExecuteOperationResponse0\x01B2Z0github.com/ivanvc/turnip/internal/grpc/turnip/v1b\x06proto3"

var (
	file_turnip_v1_operation_proto_rawDescOnce sync.Once
	file_turnip_v1_operation_proto_rawDescData []byte
)

func file_turnip_v1_operation_proto_rawDescGZIP() []byte {
	file_turnip_v1_operation_proto_rawDescOnce.Do(func() {
		file_turnip_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turnip_v1_operation_proto_rawDesc), len(file_turnip_v1_operation_proto_rawDesc)))
	})
	return file_turnip_v1_operation_proto_rawDescData
}

var file_turnip_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_turnip_v1_operation_proto_goTypes = []any{
	(*ExecuteOperationRequest)(nil),  // 0: turnip.v1.ExecuteOperationRequest
	(*ExecuteOperationResponse)(nil), // 1: turnip.v1.ExecuteOperationResponse
}
var file_turnip_v1_operation_proto_depIdxs = []int32{
	0, // 0: turnip.v1.OperationService.ExecuteOperation:input_type -> turnip.v1.ExecuteOperationRequest
	1, // 1: turnip.v1.OperationService.ExecuteOperation:output_type -> turnip.v1.ExecuteOperationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turnip_v1_operation_proto_init() }
func file_turnip_v1_operation_proto_init() {
	if File_turnip_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turnip_v1_operation_proto_rawDesc), len(file_turnip_v1_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_turnip_v1_operation_proto_goTypes,
		DependencyIndexes: file_turnip_v1_operation_proto_depIdxs,
		MessageInfos:      file_turnip_v1_operation_proto_msgTypes,
	}.Build()
	File_turnip_v1_operation_proto = out.File
	file_turnip_v1_operation_proto_goTypes = nil
	file_turnip_v1_operation_proto_depIdxs = nil
}
