// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: pkg/turnip/turnip.proto

package turnip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_UNKNOWN   JobStatus = 0
	JobStatus_FAILED    JobStatus = 1
	JobStatus_SUCCEEDED JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "FAILED",
		2: "SUCCEEDED",
	}
	JobStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"FAILED":    1,
		"SUCCEEDED": 2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_turnip_turnip_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_pkg_turnip_turnip_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{0}
}

type JobStartedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckUrl  string `protobuf:"bytes,1,opt,name=check_url,json=checkUrl,proto3" json:"check_url,omitempty"`
	CheckName string `protobuf:"bytes,2,opt,name=check_name,json=checkName,proto3" json:"check_name,omitempty"`
}

func (x *JobStartedRequest) Reset() {
	*x = JobStartedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedRequest) ProtoMessage() {}

func (x *JobStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedRequest.ProtoReflect.Descriptor instead.
func (*JobStartedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{0}
}

func (x *JobStartedRequest) GetCheckUrl() string {
	if x != nil {
		return x.CheckUrl
	}
	return ""
}

func (x *JobStartedRequest) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

type JobStartedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobStartedReply) Reset() {
	*x = JobStartedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedReply) ProtoMessage() {}

func (x *JobStartedReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedReply.ProtoReflect.Descriptor instead.
func (*JobStartedReply) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{1}
}

type JobFinishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckUrl         string    `protobuf:"bytes,1,opt,name=check_url,json=checkUrl,proto3" json:"check_url,omitempty"`
	CheckName        string    `protobuf:"bytes,2,opt,name=check_name,json=checkName,proto3" json:"check_name,omitempty"`
	CommentsUrl      string    `protobuf:"bytes,3,opt,name=comments_url,json=commentsUrl,proto3" json:"comments_url,omitempty"`
	Command          string    `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	ProjectDir       string    `protobuf:"bytes,5,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	ProjectWorkspace string    `protobuf:"bytes,6,opt,name=project_workspace,json=projectWorkspace,proto3" json:"project_workspace,omitempty"`
	Status           JobStatus `protobuf:"varint,7,opt,name=status,proto3,enum=turnip.JobStatus" json:"status,omitempty"`
	Output           []byte    `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`
	Error            string    `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *JobFinishedRequest) Reset() {
	*x = JobFinishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobFinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFinishedRequest) ProtoMessage() {}

func (x *JobFinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFinishedRequest.ProtoReflect.Descriptor instead.
func (*JobFinishedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{2}
}

func (x *JobFinishedRequest) GetCheckUrl() string {
	if x != nil {
		return x.CheckUrl
	}
	return ""
}

func (x *JobFinishedRequest) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *JobFinishedRequest) GetCommentsUrl() string {
	if x != nil {
		return x.CommentsUrl
	}
	return ""
}

func (x *JobFinishedRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobFinishedRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *JobFinishedRequest) GetProjectWorkspace() string {
	if x != nil {
		return x.ProjectWorkspace
	}
	return ""
}

func (x *JobFinishedRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_UNKNOWN
}

func (x *JobFinishedRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *JobFinishedRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobFinishedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobFinishedReply) Reset() {
	*x = JobFinishedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobFinishedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFinishedReply) ProtoMessage() {}

func (x *JobFinishedReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFinishedReply.ProtoReflect.Descriptor instead.
func (*JobFinishedReply) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{3}
}

var File_pkg_turnip_turnip_proto protoreflect.FileDescriptor

var file_pkg_turnip_turnip_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2f, 0x74, 0x75, 0x72,
	0x6e, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x69,
	0x70, 0x22, 0x4f, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xb4, 0x02, 0x0a, 0x12, 0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x64, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x12, 0x0a, 0x10,
	0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2a, 0x33, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45,
	0x44, 0x45, 0x44, 0x10, 0x02, 0x32, 0x9f, 0x01, 0x0a, 0x06, 0x54, 0x75, 0x72, 0x6e, 0x69, 0x70,
	0x12, 0x48, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x11, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12,
	0x1a, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x75,
	0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x76, 0x61, 0x6e, 0x76, 0x63, 0x2f, 0x74, 0x75, 0x72,
	0x6e, 0x69, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_turnip_turnip_proto_rawDescOnce sync.Once
	file_pkg_turnip_turnip_proto_rawDescData = file_pkg_turnip_turnip_proto_rawDesc
)

func file_pkg_turnip_turnip_proto_rawDescGZIP() []byte {
	file_pkg_turnip_turnip_proto_rawDescOnce.Do(func() {
		file_pkg_turnip_turnip_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_turnip_turnip_proto_rawDescData)
	})
	return file_pkg_turnip_turnip_proto_rawDescData
}

var file_pkg_turnip_turnip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_turnip_turnip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_turnip_turnip_proto_goTypes = []interface{}{
	(JobStatus)(0),             // 0: turnip.JobStatus
	(*JobStartedRequest)(nil),  // 1: turnip.JobStartedRequest
	(*JobStartedReply)(nil),    // 2: turnip.JobStartedReply
	(*JobFinishedRequest)(nil), // 3: turnip.JobFinishedRequest
	(*JobFinishedReply)(nil),   // 4: turnip.JobFinishedReply
}
var file_pkg_turnip_turnip_proto_depIdxs = []int32{
	0, // 0: turnip.JobFinishedRequest.status:type_name -> turnip.JobStatus
	1, // 1: turnip.Turnip.ReportJobStarted:input_type -> turnip.JobStartedRequest
	3, // 2: turnip.Turnip.ReportJobFinished:input_type -> turnip.JobFinishedRequest
	2, // 3: turnip.Turnip.ReportJobStarted:output_type -> turnip.JobStartedReply
	4, // 4: turnip.Turnip.ReportJobFinished:output_type -> turnip.JobFinishedReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_turnip_turnip_proto_init() }
func file_pkg_turnip_turnip_proto_init() {
	if File_pkg_turnip_turnip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_turnip_turnip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobFinishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobFinishedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_turnip_turnip_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_turnip_turnip_proto_goTypes,
		DependencyIndexes: file_pkg_turnip_turnip_proto_depIdxs,
		EnumInfos:         file_pkg_turnip_turnip_proto_enumTypes,
		MessageInfos:      file_pkg_turnip_turnip_proto_msgTypes,
	}.Build()
	File_pkg_turnip_turnip_proto = out.File
	file_pkg_turnip_turnip_proto_rawDesc = nil
	file_pkg_turnip_turnip_proto_goTypes = nil
	file_pkg_turnip_turnip_proto_depIdxs = nil
}
