// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: pkg/turnip/turnip.proto

package turnip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorePlanOutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanOutput string `protobuf:"bytes,1,opt,name=plan_output,json=planOutput,proto3" json:"plan_output,omitempty"`
}

func (x *StorePlanOutputRequest) Reset() {
	*x = StorePlanOutputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorePlanOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePlanOutputRequest) ProtoMessage() {}

func (x *StorePlanOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePlanOutputRequest.ProtoReflect.Descriptor instead.
func (*StorePlanOutputRequest) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{0}
}

func (x *StorePlanOutputRequest) GetPlanOutput() string {
	if x != nil {
		return x.PlanOutput
	}
	return ""
}

type JobStartedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryFullName string `protobuf:"bytes,1,opt,name=repository_full_name,json=repositoryFullName,proto3" json:"repository_full_name,omitempty"`
	CommitSha          string `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	CheckUrl           string `protobuf:"bytes,3,opt,name=check_url,json=checkUrl,proto3" json:"check_url,omitempty"`
}

func (x *JobStartedRequest) Reset() {
	*x = JobStartedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedRequest) ProtoMessage() {}

func (x *JobStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedRequest.ProtoReflect.Descriptor instead.
func (*JobStartedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{1}
}

func (x *JobStartedRequest) GetRepositoryFullName() string {
	if x != nil {
		return x.RepositoryFullName
	}
	return ""
}

func (x *JobStartedRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *JobStartedRequest) GetCheckUrl() string {
	if x != nil {
		return x.CheckUrl
	}
	return ""
}

type JobStartedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobStartedReply) Reset() {
	*x = JobStartedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedReply) ProtoMessage() {}

func (x *JobStartedReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedReply.ProtoReflect.Descriptor instead.
func (*JobStartedReply) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{2}
}

type StorePlanOutputReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StorePlanOutputReply) Reset() {
	*x = StorePlanOutputReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorePlanOutputReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePlanOutputReply) ProtoMessage() {}

func (x *StorePlanOutputReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePlanOutputReply.ProtoReflect.Descriptor instead.
func (*StorePlanOutputReply) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{3}
}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{4}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_turnip_turnip_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_turnip_turnip_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pkg_turnip_turnip_proto_rawDescGZIP(), []int{5}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_turnip_turnip_proto protoreflect.FileDescriptor

var file_pkg_turnip_turnip_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2f, 0x74, 0x75, 0x72,
	0x6e, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x69,
	0x70, 0x22, 0x39, 0x0a, 0x16, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x81, 0x01, 0x0a,
	0x11, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x73,
	0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x53, 0x68, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c,
	0x22, 0x11, 0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd7, 0x01, 0x0a, 0x06, 0x54, 0x75, 0x72, 0x6e,
	0x69, 0x70, 0x12, 0x42, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x19, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x75,
	0x72, 0x6e, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x2e, 0x74, 0x75, 0x72, 0x6e,
	0x69, 0x70, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x75, 0x72, 0x6e,
	0x69, 0x70, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x2e, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x74, 0x75,
	0x72, 0x6e, 0x69, 0x70, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x76, 0x61, 0x6e, 0x76, 0x63, 0x2f, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x74, 0x75, 0x72, 0x6e, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_turnip_turnip_proto_rawDescOnce sync.Once
	file_pkg_turnip_turnip_proto_rawDescData = file_pkg_turnip_turnip_proto_rawDesc
)

func file_pkg_turnip_turnip_proto_rawDescGZIP() []byte {
	file_pkg_turnip_turnip_proto_rawDescOnce.Do(func() {
		file_pkg_turnip_turnip_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_turnip_turnip_proto_rawDescData)
	})
	return file_pkg_turnip_turnip_proto_rawDescData
}

var file_pkg_turnip_turnip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_turnip_turnip_proto_goTypes = []interface{}{
	(*StorePlanOutputRequest)(nil), // 0: turnip.StorePlanOutputRequest
	(*JobStartedRequest)(nil),      // 1: turnip.JobStartedRequest
	(*JobStartedReply)(nil),        // 2: turnip.JobStartedReply
	(*StorePlanOutputReply)(nil),   // 3: turnip.StorePlanOutputReply
	(*HelloRequest)(nil),           // 4: turnip.HelloRequest
	(*HelloReply)(nil),             // 5: turnip.HelloReply
}
var file_pkg_turnip_turnip_proto_depIdxs = []int32{
	1, // 0: turnip.Turnip.JobStarted:input_type -> turnip.JobStartedRequest
	0, // 1: turnip.Turnip.StorePlanOutput:input_type -> turnip.StorePlanOutputRequest
	4, // 2: turnip.Turnip.SayHello:input_type -> turnip.HelloRequest
	2, // 3: turnip.Turnip.JobStarted:output_type -> turnip.JobStartedReply
	3, // 4: turnip.Turnip.StorePlanOutput:output_type -> turnip.StorePlanOutputReply
	5, // 5: turnip.Turnip.SayHello:output_type -> turnip.HelloReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_turnip_turnip_proto_init() }
func file_pkg_turnip_turnip_proto_init() {
	if File_pkg_turnip_turnip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_turnip_turnip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorePlanOutputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorePlanOutputReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_turnip_turnip_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_turnip_turnip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_turnip_turnip_proto_goTypes,
		DependencyIndexes: file_pkg_turnip_turnip_proto_depIdxs,
		MessageInfos:      file_pkg_turnip_turnip_proto_msgTypes,
	}.Build()
	File_pkg_turnip_turnip_proto = out.File
	file_pkg_turnip_turnip_proto_rawDesc = nil
	file_pkg_turnip_turnip_proto_goTypes = nil
	file_pkg_turnip_turnip_proto_depIdxs = nil
}
