apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turnip.fullname" . }}-config
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
data:
  TURNIP_NAMESPACE: {{ include "turnip.namespace" . }}
  TURNIP_LISTEN_HTTP: ":{{ .Values.service.httpPort }}"
  TURNIP_LISTEN_RPC: ":{{ .Values.service.rpcPort }}"
  {{- if .Values.config.log_level }}
  TURNIP_LOG_LEVEL: {{ .Values.config.log_level }}
  {{- end }}
