apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turnip.fullname" . }}-config
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
data:
  TURNIP_NAMESPACE: {{ include "turnip.namespace" . }}
  TURNIP_LISTEN_HTTP: ":{{ .Values.service.httpPort }}"
  TURNIP_LISTEN_RPC: ":{{ .Values.service.rpcPort }}"
  {{- if .Values.config.logLevel }}
  TURNIP_LOG_LEVEL: {{ .Values.config.logLevel }}
  {{- end }}
  TURNIP_RUNNER_JOB_SECRETS_NAME: {{ include "turnip.fullname" . }}-runner-secrets
  TURNIP_RUNNER_JOB_POD_ANNOTATIONS: >
    {{- toJson .Values.runner.podAnnotations | nindent 4}}
