apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  ARES_GITHUB_TOKEN: {{ .Values.secrets.github_token | quote }}
