apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  {{- with .Values.secrets.apiToken }}
  TURNIP_API_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.additionalSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-runner-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  {{- with .Values.runner.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
