apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  TURNIP_API_TOKEN: {{ .Values.secrets.apiToken | quote }}
  {{- toYaml .Values.additionalSecrets | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-runner-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  {{- toYaml .Values.runner.secrets | nindent 2 }}
