apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnip.fullname" . }}-job-secrets
  labels:
    {{- include "turnip.labels" . | nindent 4 }}
stringData:
  TURNIP_GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}

  {{- toYaml .Values.jobSecrets | nindent 2 }}
